# 指定基础镜像
FROM nginx

# 复制文件或目录到容器
# COPY ./web/index.html /usr/share/nginx/html/

# 指定工作目录
# WORKDIR /app

# 构建镜像时执行
#RUN echo '修改文本' > /usr/share/nginx/html/index.html

# 暴露端口
# EXPOSE 80

# ENTRYPOINT ["可执行命令", "参数1", "参数2"...]
# 作用类似CMD,但参数不会被docker run 的命令行参数覆盖
ENTRYPOINT ["nginx", "-c"] 

# CMD ["可执行命令", "参数1", "参数2"...] | shell命令 | ["参数1", "参数2"]
# 第三种写法相当于给ENTRYPOINT传参
# 运行容器时执行
CMD ["/etc/nginx/nginx.conf"]

